# Generated by Django 4.2.6 on 2023-10-30 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Vastralaya_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 15, 31, 53, 917766, tzinfo=datetime.timezone.utc)),
        ),
    ]
