# Generated by Django 4.2.6 on 2023-10-30 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Vastralaya_home', '0002_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 15, 34, 36, 465283, tzinfo=datetime.timezone.utc)),
        ),
    ]
